In [196]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math as Math
# Aim is to predict the marks of students of the test data

In [198]:
# Use the file namd 'training data' to train the model
'''No affect:-absences
x^4 for freetime and study lol
x^2 for study and age and travel(ln(x) better tbh)
internet,IQ and gender - x^1
sqrt:-travel and IQ
Mult:
'''
data = pd.read_excel('Training data.xlsx')
x_train = np.array(data.iloc[:,0:8])
y_train = np.array(data.iloc[:,8]).reshape(-1,1)
print(x_train)

# Try plotting y_train with different features
# To get an idea whether to add some features or not
# Add some features if required in x_train

# Also do label encoding for features not represented in numbers
# refer the link if not know : https://youtu.be/589nCGeWG1w?si=t2Wa7LgbUOO4RooM

def feature_changing(x_train):
  # ---------
    # Your code here
  # ---------
    for i in range(x_train.shape[0]):
        if(x_train[i,0]=='yes'):
            x_train[i,0]=1
        else:
            x_train[i,0]=-1
    for i in range(x_train.shape[0]):
        if(x_train[i,1]=='M'):
            x_train[i,1]=1
        else:
            x_train[i,1]=-1
    x=x_train
    for i in range(x_train.shape[1]):
        for j in range(i,x_train.shape[1]):
            x=np.concatenate((x,x_train[:,i:i+1]*x_train[:,j:j+1]),axis=1) 
    
    
    #x=np.concatenate((x,x[:,2:7]**2),axis=1)
    x=np.concatenate((x,(x[:,3:7]**3)/(20**3)),axis=1)
    x=np.concatenate((x,(x[:,2:3])**0.5),axis=1)
    x=np.concatenate((x,(x[:,6:8])**0.5),axis=1)
    
    for i in range(x.shape[1]):
        x[:,i]=x[:,i]/(np.max(x[:,i]))
    return x

x_train = feature_changing(x_train)
print(x_train)


[['no' 'M' 2 ... 6 18 118]
 ['yes' 'M' 2 ... 7 19 107]
 ['yes' 'M' 3 ... 5 18 108]
 ...
 ['yes' 'M' 2 ... 5 17 123]
 ['yes' 'F' 1 ... 8 17 104]
 ['yes' 'M' 1 ... 6 18 128]]
[[-1.0 1.0 0.5 ... 0.7071067811865476 0.973328526784575
  0.9564144928693534]
 [1.0 1.0 0.5 ... 0.7071067811865476 1.0 0.9107454992153875]
 [1.0 1.0 0.75 ... 0.8660254037844386 0.973328526784575 0.914991421995628]
 ...
 [1.0 1.0 0.5 ... 0.7071067811865476 0.9459053029269172
  0.9764672918705589]
 [1.0 -1.0 0.25 ... 0.5 0.9459053029269172 0.8978872704229617]
 [1.0 1.0 0.25 ... 0.5 0.973328526784575 0.9961164901835046]]


In [199]:
print(x_train.shape)

(1000, 51)


In [200]:
def z_score(x_train):

  # ---------
    # write the code for feature scaling here
    # Your code here
  # ---------
    x_mean=np.mean(x_train)
    x_std=np.mean(x_train)
    x_train=(x_train-x_mean)/x_std
    return x_train,x_std,x_mean

In [201]:
def cost(x_train,y_train,w,b):

  # ---------
    # Your code here
    # Use mean square error as cost function
    # return cost
  # ---------
    m=x_train.shape[0]
    s=0.0
    for i in range(m):
        s+=(((np.dot(w,x_train[i])+b-y_train[i])**2))
    s=s/2*m
    return s

In [202]:
def gradient_descent(x_train,y_train,w,b):
    a=0.01
  # ---------
    # Your code here
    # Choose learning rate yourself
  # ---------
    m=len(y_train)
    n=x_train.shape[1]
    dw=np.zeros(n)
    tw=0.0
    for j in range(n):
        for i in range(m):
            tw=tw+((np.dot(w,x_train[i])+b-y_train[i])*x_train[i,j])
        dw[j]=tw
    dw=dw/m
    tb=0.0
    for i in range(m):
            tb=tb+((np.dot(w,x_train[i])+b-y_train[i]))
    db=tb/m
    tw=w-a*dw
    tb=b-a*db
    w=tw
    b=tb
    return w,b

In [203]:
x_train,x_std,x_mean = z_score(x_train)
print(np.max(x_train[:,:])-np.min(x_train[:,:]))
print(y_train)

4.563674607362476
[[73.13]
 [67.78]
 [70.84]
 [66.68]
 [71.88]
 [73.84]
 [71.47]
 [74.48]
 [73.48]
 [91.44]
 [79.38]
 [62.51]
 [75.  ]
 [62.64]
 [53.95]
 [68.26]
 [67.65]
 [76.44]
 [77.44]
 [78.45]
 [77.23]
 [70.31]
 [80.  ]
 [69.9 ]
 [65.42]
 [67.38]
 [73.17]
 [81.11]
 [82.87]
 [72.4 ]
 [65.  ]
 [75.49]
 [73.74]
 [68.4 ]
 [64.06]
 [79.62]
 [60.55]
 [79.06]
 [61.99]
 [77.3 ]
 [81.22]
 [67.43]
 [72.16]
 [67.11]
 [67.78]
 [62.99]
 [65.14]
 [56.96]
 [73.75]
 [64.25]
 [71.61]
 [66.72]
 [61.73]
 [75.25]
 [80.37]
 [80.59]
 [67.13]
 [75.13]
 [78.27]
 [58.17]
 [76.88]
 [62.38]
 [63.09]
 [73.21]
 [72.03]
 [66.38]
 [78.91]
 [76.35]
 [65.27]
 [80.82]
 [60.83]
 [65.23]
 [74.39]
 [71.04]
 [68.27]
 [81.3 ]
 [72.11]
 [69.73]
 [63.11]
 [65.88]
 [61.36]
 [74.8 ]
 [72.86]
 [69.6 ]
 [67.93]
 [76.35]
 [66.52]
 [72.81]
 [74.36]
 [73.42]
 [78.12]
 [66.41]
 [66.98]
 [67.36]
 [65.7 ]
 [78.4 ]
 [76.09]
 [74.08]
 [55.33]
 [66.71]
 [58.59]
 [64.59]
 [59.55]
 [67.06]
 [67.72]
 [63.57]
 [60.73]
 [64.01]
 [77.23]
 

In [211]:
x_train = x_train.astype(np.float64)
#x_train,x_std,x_mean = z_score(x_train)

np.random.seed(2147483647)
w = np.random.randn(x_train.shape[1],)
b = np.random.randn(1)

old_cost = 0
i=0
while abs(old_cost - cost(x_train,y_train,w,b))>1:
    old_cost = cost(x_train,y_train,w,b)
    w,b = gradient_descent(x_train,y_train,w,b)
    if(i%100==0):
        print(f"cost({w},{b},x_train,y_train)={cost(x_train,y_train,w,b)}")
    i+=1
'''w=np.array([-0.79384013,-0.03146606,-3.47636683, 5.8895991, -1.5585789, 16.32260731,
 22.70597599, 0.70833468, 1.76190363,-1.95699588, 4.92120563, 2.27833866,
  1.77665849, 0.53578001,-2.30993616, -0.70841404, -6.84501382, 0.80395445,
 16.73966405])
b=np.array([32.56130664])'''
x_predict = pd.read_excel('Test data.xlsx').iloc[:,:8].to_numpy()
x_predict = feature_changing(x_predict)
x_predict = (x_predict - x_mean)/x_std
ans = pd.read_excel('Test data.xlsx').iloc[:,8].to_numpy()

y_predict = np.dot(x_predict,w) + b

accuracy = 0
for dim in range(len(ans)):
  if abs(y_predict[dim]-ans[dim])<0.5: # do not change the tolerance as you'll be checked on +- 0.5 error only
    accuracy += 1
accuracy = round(accuracy*100/200.0,2)
ok = 'Congratulations' if accuracy>95 else 'Optimization required'
print(f"{ok}, your accuracy is {accuracy}%")

C:\Users\adars\AppData\Local\Temp\ipykernel_6720\2080162078.py:14: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dw[j]=tw


cost([ 1.36017654 -1.85386413  0.63518623  0.09649266 -1.43319635 -0.25411834
 -0.29781618  1.56905834  2.16144955  3.16953942  1.23666054  0.72916615
  1.40980661 -1.3835993  -0.24055912 -0.23899904 -0.50357714 -0.60970382
 -1.43839457 -0.5123862  -3.34487    -1.59668828 -4.12926134 -2.64817086
 -4.43115637 -3.47939953 -3.64228174 -5.65115816 -6.3611572  -6.29549342
 -4.19593597 -4.39430559 -4.15384724 -4.64434804 -5.85814869 -4.19800662
 -5.67835637 -4.69304326 -4.6856169  -5.67505938 -4.19852003 -2.80523687
 -3.06892776 -3.30352386 -4.35821861 -2.81217912 -2.29528282 -3.32840084
 -2.35189342 -1.9393189  -1.46428985],[1.57820332],x_train,y_train)=[2.85244276e+09]
cost([ 2.7474122   0.09474213  3.22608899  4.59190538  2.4945334   3.76449068
  5.50635045  9.17966402 11.86449296  0.57463401 -1.55424569 -1.29092371
 -0.86599033 -2.87212004 -0.55487701  0.55640549  2.38426513  1.52930771
  0.51618827  0.80880463 -1.59577233  0.54713363 -1.65409053 -0.20220459
 -1.69508226 -1.47702075 -2.1

In [ ]:
#Got these values after running on PC for 4 hrs(no loop breaks), 95% accuracy
'''w2=np.array([3.13339739e-02,-1.15901188e+00,1.61904955e+00,4.06748069e+00
,2.37758713e+00,3.24832874e+00,5.41648895e+00,1.12125540e+01
,1.61480752e+01,2.50190651e-03,-1.91263984e-02,1.94336898e-03
,-2.46528043e-02,-2.09377469e-02,-6.78711604e-01,-1.20306749e-02
,4.06652123e+00,5.87050247e-03,-5.43958443e-03,6.46287090e-03
,7.03175363e-03,1.21123775e+00,4.82691878e-03,1.65733088e-01
,-2.95040730e-01,1.26000049e-01,-1.26207348e-01,-2.64905765e+00
,-2.06078799e+00,-2.22135401e+00,9.27600918e-02,8.41489456e-02
,1.89781457e+00,2.31975374e+00,-6.48168427e-01,-2.65808824e-01
,-2.93285169e+00,-1.40596057e+00,-1.50971229e+00,-3.59682910e+00
,-1.30548156e+00,3.88195635e-01,2.19212401e+00,5.25308050e+00
,1.16753665e+00,2.14503105e-01,8.89913064e-01,-1.55736594e+00
,1.22241342e+00,4.88347366e+00,9.53141215e+00])
b2=np.array([4.96641022])'''

In [ ]:
'''x_predict = pd.read_excel('Test data.xlsx').iloc[:,:8].to_numpy()
x_predict = feature_changing(x_predict)
x_predict = (x_predict - x_mean)/x_std
ans = pd.read_excel('Test data.xlsx').iloc[:,8].to_numpy()

y_predict = np.dot(x_predict,w2) + b2

accuracy = 0
for dim in range(len(ans)):
  if abs(y_predict[dim]-ans[dim])<0.5: # do not change the tolerance as you'll be checked on +- 0.5 error only
    accuracy += 1
accuracy = round(accuracy*100/200.0,2)
ok = 'Congratulations' if accuracy>95 else 'Optimization required'
print(f"{ok}, your accuracy is {accuracy}%")'''